apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-page-pv-claim
  namespace: status-page
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
