version: "3"

networks:
  proxy:
    name: proxy
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: atlas
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - "${PWD}/traefik.log:/traefik.log"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/traefik.toml:/traefik.toml"
      - "${PWD}/traefik_dynamic.toml:/traefik_dynamic.toml"
      - "${PWD}/acme.json:/acme.json"
      - "${PWD}/ssl/cert.pem:/etc/ssl/certs/cert.pem"
      - "${PWD}/ssl/key.pem:/etc/ssl/private/key.pem"
