services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.arthurdanjou.fr`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
    networks:
      - traefik_network
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 6379
        published: 6379
        mode: host
      - target: 5432
        published: 5432
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /root/traefik/acme.json:/letsencrypt/acme.json
      - /root/traefik/logs/:/logs/
      - /root/traefik/dynamics:/etc/traefik/dynamics
    environment:
      - CF_API_EMAIL
      - CF_API_KEY
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN

networks:
  traefik_network:
    external: true
