[http.middlewares.devAuth.basicAuth]
  users = [
    "arthur:password",
  ]

[http.middlewares.simpleAuth.basicAuth]
  users = [
    "arthur:password"
  ]

[http.routers.api]
  rule = "Host(`proxy.arthurdanjou.fr`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[[tls.certificates]]
  certFile = "/etc/ssl/certs/cert.pem"
  keyFile = "/etc/ssl/private/key.pem"
