entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
  postgres:
    address: ":5432"
  redis:
    address: ":6379"

accesslog:
  addInternals: true
  filePath: "/logs/access.log"

log:
  filePath: "/logs/logs.log"
  format: json
  level: INFO

ping:
  entryPoint: "websecure"

providers:
  docker:
    exposedByDefault: false
    network: traefik_network
  file:
    directory: /etc/traefik/dynamics

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  cloudflare:
    acme:
      email: "xxx"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 0