services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      - traefik_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.arthurdanjou.fr`)"
      - "traefik.http.routers.adguardhome.entrypoints=websecure"
      - "traefik.http.routers.adguardhome.tls.certresolver=cloudflare"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"

networks:
  traefik_network:
    external: true