apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: traefik
  labels:
    app: traefik
data:
  traefik.yml: |
    entryPoints:
      web:
        address: ':80'
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ':443'
      metrics:
        address: :8082
      ping:
        address: :8083

    api:
      dashboard: true
      insecure: true
    
    ping:
      entryPoint: "ping"

    accessLog:
      filePath: "access.log"

    log:
      filePath: "traefik.log"
      level: DEBUG

    metrics:
      prometheus:
        entryPoint: metrics
        addRoutersLabels: true
        addServicesLabels: true
        buckets:
          - 0.1
          - 0.3
          - 1.2
          - 5.0

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    
    serversTransport:
      insecureSkipVerify: true
    
    certificatesResolvers:
      lets-encrypt:
        acme:
          caServer: https://acme-staging-v02.api.letsencrypt.org/directory
          email: "arthurdanjou@outlook.fr"
          storage: "/certs/acme.json"
          tlsChallenge: {}

    experimental:
      plugins:
        traefik-real-ip:
          modulename: github.com/soulbalz/traefik-real-ip
          version: v1.0.3
