apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: traefik
  labels:
    app: traefik
data:
  file.yml: |
    tls:
      stores:
        default:
          defaultCertificate:
            - certFile: etc/traefik/ssl/cert.pem
            keyFile: etc/traefik/ssl/key.pem
  traefik.yml: |
    entryPoints:
      web:
        address: ':80'
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ':443'
      metrics:
        address: :8082
      ping:
        address: :8083

    api:
      dashboard: true
      insecure: true
    
    ping:
      entryPoint: "ping"

    accessLog:
      filePath: "access.log"

    log:
      filePath: "traefik.log"
      level: INFO

    metrics:
      prometheus:
        entryPoint: metrics
        addRoutersLabels: true
        addServicesLabels: true
        buckets:
          - 0.1
          - 0.3
          - 1.2
          - 5.0

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    
    serversTransport:
      insecureSkipVerify: true

    experimental:
      plugins:
        traefik-real-ip:
          modulename: github.com/soulbalz/traefik-real-ip
          version: v1.0.3
