apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller

      volumes:
        - name: traefik-conf
          configMap:
            name: traefik-conf
        - name: traefik-ssl
          secret:
            secretName: traefik-ssl

      containers:
        - name: traefik
          image: traefik:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/traefik
              name: traefik-conf
            - mountPath: "/etc/traefik/ssl"
              name: traefik-ssl
          livenessProbe:
            httpGet:
              path: /ping
              port: 8083
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
            - name: metrics
              containerPort: 8082
            - name: ping
              containerPort: 8083
