apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`proxy.arthurdanjou.fr`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: basic-auth
  tls:
    store:
      name: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-fallback
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{host:.+}`)
      kind: Rule
      services:
        - name: fallback
          port: 3355
      middlewares:
        - name: traefik-fallback-maintenance@kubernetescrd
        - name: traefik-fallback-errors@kubernetescrd
  tls:
    store:
      name: default
