apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv.yml
  namespace: mariadb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/data/mariadb
    type: DirectoryOrCreate
