apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: mariadb
spec:
  clusterIP: None # Headless
  ports:
    - port: 3306
      name: mariadb
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb
