apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: mariadb
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/mariadb
    type: DirectoryOrCreate
