version: "3"

networks:
  proxy:
    name: proxy
    external: true

services:
  portainer:
    image: portainer/portainer-ce
    container_name: apollon
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/data:/data"
    labels:
      - traefik.http.routers.apollon.rule=Host(`cloud.arthurdanjou.fr`)
      - traefik.http.routers.apollon.tls=true
      - traefik.http.routers.apollon.tls.certresolver=lets-encrypt
      - traefik.http.services.apollon.loadbalancer.server.port=9000
      - traefik.docker.network=proxy
      - traefik.port=443
