apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: portainer
spec:
  storageClassName: local-path
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/portainer
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pv-claim
  namespace: portainer
spec:
  storageClassName: local-path
  volumeName: portainer-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
