version: "3"

services:
  minecraft_server:
    image: itzg/minecraft-server
    container_name: minecraft_server_1
    restart: unless-stopped
    labels:
      - traefik.enable=false
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.18.1
      VIEW_DISTANCE: 10
      MEMORY: 2G
    ports:
      - 25565:25565
    networks:
      - survie1
    volumes:
      - "${PWD}/data:/data"

networks:
  survie1:
    external: false
    driver: bridge
