version: "3"

networks:
  proxy:
    name: proxy
    external: true
  artnetwork:
    name: artnetwork
    external: true

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    volumes:
      - "${PWD}/config.production.json:/var/lib/ghost/config.production.json:z"
      - "${PWD}/content:/var/lib/ghost/content:z"
    ports:
      - 2368:2368
    networks:
      - proxy
      - artnetwork
    labels:
      - traefik.http.routers.ghost.rule=Host(`blog.arthurdanjou.fr`)
      - traefik.http.routers.ghost.tls=true
      - traefik.http.routers.ghost.tls.certresolver=lets-encrypt
      - traefik.docker.network=proxy
      - traefik.port=443
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=production # set either production or development, then it will load the respective config
