services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`logs.arthurdanjou.fr`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.http.routers.beszel.tls.certresolver=cloudflare"
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ""

volumes:
  beszel_data:

networks:
  traefik_network:
    external: true