apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-shortener-pv
  namespace: artdanj-shortener
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/redis/shortener
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-shortener-pv-claim
  namespace: artdanj-shortener
spec:
  storageClassName: local-path
  volumeName: redis-shortener-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
